# Generated by Django 3.0.8 on 2020-07-30 11:09

import FAQ.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=75)),
                ('BrowserTitle', models.CharField(max_length=75)),
                ('MetaDescription', models.TextField()),
                ('UrlSlug', models.CharField(max_length=75)),
                ('Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=75, unique=True, verbose_name='faq_Category_title')),
            ],
            options={
                'verbose_name': ('FAQ_Category',),
                'verbose_name_plural': 'FAQ_Categories',
            },
        ),
        migrations.CreateModel(
            name='Home_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=75)),
                ('BrowserTitle', models.CharField(max_length=75)),
                ('MetaDescription', models.TextField(max_length=500)),
                ('UrlSlug', models.TextField(max_length=500)),
                ('SubTitle', models.TextField(max_length=500)),
                ('SearchPlaceholder', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestForProposals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('descriptions', models.TextField(max_length=500)),
                ('attachments', models.FileField(upload_to='')),
                ('preferredCurrency', models.CharField(max_length=100)),
                ('preferredUntilPrice', models.CharField(max_length=100)),
                ('preferredShippingAgreement', models.CharField(max_length=100)),
                ('paymentMethod', models.TextField()),
                ('iAgree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Section', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='manufacturerProfilePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyProfilePicture', models.ImageField(default='defaultComProfPic.jpg', upload_to=FAQ.models.upload_path)),
                ('companyName', models.CharField(blank=True, default='Company', max_length=60)),
                ('companyDescription', models.TextField(default='Company Descriptions')),
                ('country', models.CharField(blank=True, default='USA', max_length=200)),
                ('companyLogo', models.ImageField(default='defaultComLogo.jpeg', upload_to=FAQ.models.upload_path)),
                ('sections', models.TextField(default='[{}]')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=75, unique=True, verbose_name='faq_title')),
                ('Answer', models.CharField(max_length=255, unique=True, verbose_name='content')),
                ('Active', models.BooleanField(default=False, verbose_name='')),
                ('Group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FAQ.FAQ_Group')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQS',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=75)),
                ('Thumbnail', models.ImageField(default='/images/thumbnail.jpg', upload_to='')),
                ('Download', models.FileField(default='', upload_to='')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('companyName', models.CharField(max_length=100)),
                ('emailAddress', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
