# Generated by Django 3.1.4 on 2020-12-23 17:42

import FAQ.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfilePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyProfilePicture', models.ImageField(default='defaultComProfilePic.jpg', upload_to=FAQ.models.upload_path)),
                ('companyName', models.CharField(blank=True, default='Company', max_length=60)),
                ('companyDescription', models.TextField(default="This company doesn't have any description")),
                ('country', models.CharField(blank=True, default='Undefined', max_length=200)),
                ('companyLogo', models.ImageField(default='company-logo.jpg', upload_to=FAQ.models.upload_path)),
                ('sections', models.TextField(default='[{}]')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faq_group',
            options={'ordering': ('Title',), 'verbose_name': ('FAQ_Category',), 'verbose_name_plural': 'FAQ_Categories'},
        ),
        migrations.AlterModelOptions(
            name='faq_item',
            options={'ordering': ('Title',), 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQS'},
        ),
        migrations.AddField(
            model_name='requestforproposals',
            name='destinationPort',
            field=models.CharField(default='Virginia', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emailAddress',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='document',
            name='Download',
            field=models.FileField(default='/images/thumbnail.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='links',
            name='find',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='manufacturerProfilePage',
        ),
    ]
