# Generated by Django 3.1.4 on 2020-12-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_requestforquotation_destinationport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq_group',
            options={'ordering': ('Title',), 'verbose_name': ('FAQ_Category',), 'verbose_name_plural': 'FAQ_Categories'},
        ),
        migrations.AlterModelOptions(
            name='faq_item',
            options={'ordering': ('Title',), 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQS'},
        ),
    ]
