# Generated by Django 3.1.4 on 2020-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_auto_20201207_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='links',
            name='find',
            field=models.CharField(max_length=64),
        ),
    ]
