# Generated by Django 3.1.4 on 2020-12-12 12:52

import FAQ.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAQ', '0005_auto_20201212_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfilePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyProfilePicture', models.ImageField(default='defaultComProfPic.jpg', upload_to=FAQ.models.upload_path)),
                ('companyName', models.CharField(blank=True, default='Company', max_length=60)),
                ('companyDescription', models.TextField(default="This company doesn't have any description")),
                ('country', models.CharField(blank=True, default='Undefined', max_length=200)),
                ('companyLogo', models.ImageField(default='defaultComLogo.jpeg', upload_to=FAQ.models.upload_path)),
                ('sections', models.TextField(default='[{}]')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='manufacturerProfilePage',
        ),
    ]
