# Generated by Django 3.1.4 on 2020-12-12 13:02

import FAQ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0006_auto_20201212_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofilepage',
            name='companyLogo',
            field=models.ImageField(default='company-logo.jpg', upload_to=FAQ.models.upload_path),
        ),
    ]
