# Generated by Django 3.1.4 on 2020-12-15 20:47

import FAQ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0007_auto_20201212_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofilepage',
            name='companyProfilePicture',
            field=models.ImageField(default='defaultComProfilePic.jpg', upload_to=FAQ.models.upload_path),
        ),
    ]
