# Generated by Django 3.1.4 on 2020-12-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0008_auto_20201215_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='emailAddress',
            field=models.EmailField(max_length=254),
        ),
    ]
