# Generated by Django 3.0.8 on 2020-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200712_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
    ]
