# Generated by Django 3.1.4 on 2020-12-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_stuff',
            field=models.BooleanField(default=True),
        ),
    ]
