# Generated by Django 3.1.4 on 2020-12-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201217_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
