# Generated by Django 3.0.8 on 2020-07-19 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerprofilepage',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq_item',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FAQ.FAQ_Group'),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
