# Generated by Django 3.1 on 2020-08-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_auto_20200731_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforquotation',
            name='destinationPort',
            field=models.CharField(default='Virginia', max_length=255),
        ),
    ]
