# Generated by Django 3.0.8 on 2020-07-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='MetaDescription',
            field=models.TextField(),
        ),
    ]
