# Generated by Django 3.0.8 on 2020-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_manufacturerprofilepage_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='CompanyLogo',
            field=models.ImageField(default='defaultComLogo.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='CompanyProfilePicture',
            field=models.ImageField(default='defaultComProfPic.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='Documents',
            field=models.TextField(default='Welcome to the documents'),
        ),
    ]
