# Generated by Django 3.0.8 on 2020-07-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_auto_20200715_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='Content',
            field=models.TextField(),
        ),
    ]
