# Generated by Django 3.0.8 on 2020-07-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_manufacturerprofilepage_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='Documents',
            field=models.TextField(default='Welcome to the documents'),
        ),
    ]
