# Generated by Django 3.0.8 on 2020-07-21 09:12

import FAQ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_auto_20200721_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='CompanyLogo',
            field=models.ImageField(default='defaultComLogo.jpg', upload_to=FAQ.models.upload_path),
        ),
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='CompanyProfilePicture',
            field=models.ImageField(default='defaultComProfPic.jpg', upload_to=FAQ.models.upload_path),
        ),
    ]
