# Generated by Django 3.0.8 on 2020-07-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0006_auto_20200721_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='CompanyDescription',
            new_name='companyDescription',
        ),
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='CompanyLogo',
            new_name='companyLogo',
        ),
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='CompanyName',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='CompanyProfilePicture',
            new_name='companyProfilePicture',
        ),
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='Sections',
            new_name='sections',
        ),
    ]
