# Generated by Django 3.0.8 on 2020-07-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0006_auto_20200715_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='CompanyName',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='emailAddress',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='subject',
        ),
    ]
