# Generated by Django 3.0.8 on 2020-07-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0007_auto_20200721_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='companyName',
            new_name='CompanyName',
        ),
    ]
