# Generated by Django 3.0.8 on 2020-07-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0008_auto_20200721_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturerprofilepage',
            old_name='CompanyName',
            new_name='companyName',
        ),
    ]
