# Generated by Django 3.0.8 on 2020-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0009_auto_20200721_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='companyName',
            field=models.CharField(blank=True, default='Company', max_length=60),
        ),
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=200),
        ),
    ]
