# Generated by Django 3.0.8 on 2020-07-23 08:00

import FAQ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0010_auto_20200722_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='companyLogo',
            field=models.ImageField(default='defaultComLogo.jpeg', upload_to=FAQ.models.upload_path),
        ),
    ]
