# Generated by Django 3.0.8 on 2020-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0011_auto_20200723_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerprofilepage',
            name='sections',
            field=models.TextField(default='[{}]'),
        ),
    ]
